const AR = [
  "من", "إلى", "عن", "على", "في", "مع", "بدون", "حول", "بين", "تحت", "فوق",
  "لدى", "منذ", "حتى", "خلف", "أمام", "نحو", "خلال", "بعد", "قبل", "عند",
  "ضد", "عبر", "بسبب", "رغم", "خارج", "داخل",
  "و", "ف", "ثم", "لكن", "بل", "أو", "أما", "إما", "سواء", "ل", "ك",
  "أنا", "نحن", "أنت", "أنتِ", "أنتما", "أنتم", "أنتن", "هو", "هي", "هما",
  "هم", "هن", "إياي", "إيانا", "إياك", "إياه", "إياها",
  "هذا", "هذه", "هذان", "هاتان", "هؤلاء", "ذلك", "تلك", "أولئك", "هنا",
  "هناك", "ثمة",
  "الذي", "التي", "الذين", "اللذان", "اللتان", "اللاتي", "اللواتي", "اللائي",
  "هل", "أ", "ماذا", "ماذاً", "كيف", "لماذا", "أين", "متى", "كم", "أي",
  "أية", "أينما", "حيثما", "كيفما",
  "لا", "لم", "لن", "ما", "ليس", "لست", "لسنا", "لستم", "لستن", "ليسا",
  "ليسوا", "لسن", "غير", "سوى",
  "كان", "كانت", "كانوا", "كن", "يكون", "تكون", "يصير", "صار", "صارت",
  "أصبح", "أصبحت", "أضحى", "أضحت", "ظل", "ظلت", "بات", "باتت", "زال",
  "قال", "قلت", "قلنا", "قالت", "قالوا",
  "الآن", "اليوم", "أمس", "غداً", "غدا", "ساعة", "دقيقة", "ثانية", "وقت",
  "فترة", "مدة", "لحظة", "حين", "آونة",
  "كل", "جميع", "بعض", "أغلب", "معظم", "نصف", "كثير", "قليل", "مزيد",
  "عدد", "قدر", "كمية", "مجموع",
  "واحد", "اثنان", "اثنين", "ثلاثة", "أربعة", "خمسة", "ستة", "سبعة",
  "ثمانية", "تسعة", "عشرة", "مئة", "مائة", "ألف", "مليون", "أول", "ثاني",
  "ثالث",
  "بس", "بالس", "اللي", "يلي", "هاد", "هاظ", "هيك", "هكذا", "كذا", "كده",
  "أيش", "شو", "قديش", "ليش", "هون", "دلوقت", "دلوقتي", "بكرة", "النهاردة",
  "النهار",
  "شيء", "شيئاً", "شيئ", "شخص", "أحد", "أمر", "عمل", "حال", "حد", "ناس",
  "طريق", "مكان", "اسم", "نوع", "صورة", "وجه", "شكل", "يوم", "مرة", "مر",
  "حاجة", "حاجات",
  "كما", "فيما", "مما", "منهم", "له", "لها", "لهم", "لهن", "منه", "منها",
  "عنه", "عنها", "عنهم", "إليه", "إليها", "إليهم", "فيه", "فيها", "فيهم",
  "لديه", "لديها",
  "قد", "ربما", "لعل", "ليت", "لولا", "لو",
  "إن", "أن", "إنّ", "أنّ", "كأن", "لكنّ", "لأن",
  "إذ", "إذا", "إذن", "حيث", "بينما", "بينما", "أثناء", "لمّا", "لما",
  "س", "سوف", "سين",
  "ذا", "ذو", "ذات", "ذوا",
  "ت", "تاء", "يا", "أيا", "هيا", "آ",
  "ثمة", "قط", "فقط", "فحسب", "حسب",
  "بعداً", "أبداً", "أيضاً", "أيضا", "بتاتاً", "بتات", "تماماً", "تماما",
  "تقريباً", "تقريبا", "عادة", "أيضاً", "بالفعل",
  "تحت", "فوق", "دون", "قرب", "قبالة", "تجاه", "حيال",
  "بيد", "بيد أن", "مع أن", "رغم أن", "بالرغم",
  "باء", "تاء الفاعل", "نون النسوة", "ياء المخاطبة",
];

const AR_EXTRA = [
  "ولكن", "ولكنّ", "فإن", "فإنّ", "فلا", "فلم", "فلن", "فهل",
  "وبين", "وعلى", "وفي", "ومن", "إلى", "حتى", "ومع", "وبعد", "وقبل", "وعن",
  "وليس", "وكان", "وكانت", "وإذا", "وحين", "وعند", "وبينما",
  "فيه", "فيها", "فيهم", "فيهن",
  "لذلك", "لهذا", "لهذه", "لتلك", "لذا",
  "أمام", "وراء", "يمين", "يسار", "شمال", "جنوب", "شرق", "غرب",
  "مثل", "مثلًا", "مثلاً", "نحو", "نحوه",
  "برغم", "برغم أن",
  "أصلاً", "أصلا", "إطلاقاً", "إطلاقا",
  "بتاتاً", "بتاتا", "البته", "البتة",
  "جدا", "جداً", "جدًا",
  "أكثر", "أقل", "أكبر", "أصغر",
  "طوال", "أثناء",
  "بخصوص", "خصوصاً", "خصوصا", "خاصة", "خاصةً",
  "عدا", "خلا", "حاشا",
  "بالمقابل", "المقابل",
  "تارة", "أخرى", "مراراً",
  "غالباً", "غالبا", "عادةً", "عادة",
  "أبداً", "أبدا", "أصلاً", "أصلا",
  "البعض", "الكل",
];

const EN: string[] = [
  "a", "an", "the",
  "and", "or", "but", "nor", "yet", "so", "for",
  "is", "am", "are", "was", "were", "be", "been", "being",
  "have", "has", "had", "having",
  "do", "does", "did", "doing",
  "will", "would", "shall", "should", "may", "might", "must", "can", "could",
  "i", "me", "my", "myself", "mine",
  "you", "your", "yours", "yourself", "yourselves",
  "he", "him", "his", "himself",
  "she", "her", "hers", "herself",
  "it", "its", "itself",
  "we", "us", "our", "ours", "ourselves",
  "they", "them", "their", "theirs", "themselves",
  "this", "that", "these", "those",
  "what", "which", "who", "whom", "whose", "whoever", "whomever",
  "where", "when", "why", "how",
  "here", "there",
  "all", "each", "every", "both", "few", "several", "some", "any", "no", "none",
  "many", "much", "more", "most", "little", "less",
  "other", "another", "others",
  "such", "only", "own", "same",
  "not", "no",
  "in", "on", "at", "to", "for", "with", "by", "from", "of", "about", "into",
  "through", "during", "before", "after", "above", "below", "between",
  "under", "over", "out", "off", "up", "down", "against", "without",
  "around", "within", "along", "across", "beyond", "among", "upon",
  "then", "now", "just", "also", "very", "too", "really",
  "get", "got", "gets", "getting",
  "make", "makes", "made", "making",
  "take", "takes", "took", "taking",
  "go", "goes", "went", "gone", "going",
  "come", "comes", "came", "coming",
  "see", "sees", "saw", "seen",
  "know", "knows", "knew", "known",
  "think", "thinks", "thought", "thinking",
  "want", "wants", "wanted", "wanting",
  "give", "gives", "gave", "given",
  "find", "finds", "found", "finding",
  "tell", "tells", "told", "telling",
  "use", "uses", "used", "using",
  "say", "says", "said", "saying",
  "like", "likes", "liked",
  "need", "needs", "needed",
  "mean", "means", "meant",
  "call", "calls", "called",
  "try", "tries", "tried",
  "ask", "asks", "asked",
  "feel", "feels", "felt",
  "become", "becomes", "became",
  "leave", "leaves", "left",
  "put", "puts",
  "set", "sets",
  "start", "starts", "started",
  "keep", "keeps", "kept",
  "show", "shows", "showed",
  "hear", "hears", "heard",
  "play", "plays", "played",
  "run", "runs",
  "move", "moves", "moved",
  "live", "lives", "lived",
  "believe", "believes", "believed",
  "bring", "brings", "brought",
  "happen", "happens", "happened",
  "write", "writes", "wrote", "written",
  "provide", "provides", "provided",
  "sit", "sits",
  "stand", "stands",
  "lose", "loses", "lost",
  "pay", "pays", "paid",
  "meet", "meets", "met",
  "include", "includes", "included",
  "continue", "continues", "continued",
  "set", "sets",
  "learn", "learns", "learned",
  "change", "changes", "changed",
  "lead", "leads", "led",
  "understand", "understands", "understood",
  "watch", "watches", "watched",
  "follow", "follows", "followed",
  "stop", "stops", "stopped",
  "create", "creates", "created",
  "speak", "speaks", "spoke",
  "read", "reads",
  "allow", "allows", "allowed",
  "add", "adds", "added",
  "spend", "spends", "spent",
  "grow", "grows", "grew",
  "open", "opens", "opened",
  "walk", "walks", "walked",
  "win", "wins", "won",
  "offer", "offers", "offered",
  "remember", "remembers", "remembered",
  "love", "loves", "loved",
  "consider", "considers", "considered",
  "appear", "appears", "appeared",
  "buy", "buys", "bought",
  "wait", "waits", "waited",
  "serve", "serves", "served",
  "die", "dies", "died",
  "send", "sends", "sent",
  "expect", "expects", "expected",
  "build", "builds", "built",
  "stay", "stays", "stayed",
  "fall", "falls", "fell",
  "cut", "cuts",
  "reach", "reaches", "reached",
  "kill", "kills", "killed",
  "remain", "remains", "remained",
  "suggest", "suggests", "suggested",
  "raise", "raises", "raised",
  "pass", "passes", "passed",
  "sell", "sells", "sold",
  "require", "requires", "required",
  "report", "reports", "reported",
  "decide", "decides", "decided",
  "pull", "pulls", "pulled",
  "whether", "although", "though", "while",
  "if",
  "because", "since",
  "until", "unless",
  "as", "than",
];

export const AR_STOP = new Set(AR.concat(AR_EXTRA));
export const EN_STOP = new Set(EN.map((w) => w.toLowerCase()));

export const STOP_WORDS = new Set<string>();

for (const w of AR_STOP) STOP_WORDS.add(w);
for (const w of EN_STOP) STOP_WORDS.add(w);

export function isStopWord(word: string): boolean {
  return word.length < 3 || STOP_WORDS.has(word.toLowerCase());
}

export function isMeaningfulWord(word: string): boolean {
  const w = word.toLowerCase();
  if (w.length < 3 || w.length > 30) return false;
  if (/^\d+$/.test(w)) return false;
  return !STOP_WORDS.has(w);
}
